public enum GameEvents
{
    PlayerHealthAltered,
    LightDamage,
    EnemyHealthAltered,
    EnemyFriendlyFire,
    EnemyHealed,
    PlayerWin,
    PlayerLose,
    PlayerTurn,
    EnemyTurn,
    GameStart,
    BattleStart,
    AOEunsuccessful,
    InteractableOFR,
    NoInteractable,
    NoTarget,
    TargetOFR
}