name: Tests

on: [push]

jobs:
  Test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Run tests
        uses: game-ci/unity-test-runner@v2.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: Project SIVA
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
    
