name: Tests

on: [push, pull_request]

jobs:
  Test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-SIVA
          restore-keys: |
            Library-
            Library-SIVA
          
      - name: Run tests
        uses: game-ci/unity-test-runner@v2.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: Project_SIVA
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          
